
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

// Copied from:
// https://github.com/dotnet/runtime/blob/80a8cdbdb9c36ccab97374afcb2f0491ae58a94d/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/UnionAttribute.cs

#if NET11_0_OR_GREATER

using System.Runtime.CompilerServices;

#pragma warning disable RS0016 // Add public types and members to the declared API (this is a supporting forwarder for an internal polyfill API)
[assembly: TypeForwardedTo(typeof(UnionAttribute))]
#pragma warning restore RS0016 // Add public types and members to the declared API

#else

#nullable enable

namespace System.Runtime.CompilerServices
{
    /// <summary>
    /// Provides a common interface for accessing the contents of a union type at runtime.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The C# compiler automatically implements this interface on types generated by union declarations.
    /// User-defined types annotated with <see cref="UnionAttribute" /> may also implement this interface
    /// to provide runtime access to the union's value. Implementing this interface is not required
    /// for union behaviors provided by the compiler.
    /// </para>
    /// </remarks>
    /// <seealso cref="UnionAttribute" />
    internal interface IUnion
    {
        /// <summary>
        /// Gets the value contained in the union, or <see langword="null" /> if the union has no value.
        /// </summary>
        /// <value>
        /// The current value of the union as one of its case types, or <see langword="null" />.
        /// </value>
        object? Value { get; }
    }
}

#endif
